#!/usr/bin/env node
// Generates packages/dapp/.env from packages/sdk/config/<network>.json AND
// copies the 6 snarkjs circuit artifacts the dApp needs into public/circuits/
// so Vite serves them natively at /circuits/<name>/<name>.{wasm,zkey}.
//
// Usage:
//   node scripts/sync-env.mjs                 # reads testnet.json
//   STELLAR_NETWORK=mainnet node scripts/sync-env.mjs

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Resolve the CONF asset issuer from the stellar CLI keyring so the dApp can
// build a ChangeTrust op for new users. Soft-fail if the keyring isn't set up
// — the resulting env vars just stay empty and the dApp falls back to a hint.
function tryStellarKeyAddress(name) {
  try {
    return execSync(`stellar keys address ${name}`, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "";
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../..");
const network = process.env.STELLAR_NETWORK ?? "testnet";
const cfgPath = join(repoRoot, "packages", "sdk", "config", `${network}.json`);
const envPath = join(__dirname, "..", ".env");
const publicDir = join(__dirname, "..", "public");
const circomBuild = join(repoRoot, "EncryptedERC", "circom", "build");

if (!existsSync(cfgPath)) {
  console.error(`missing ${cfgPath} — run scripts/deploy-testnet.sh first`);
  process.exit(1);
}

const cfg = JSON.parse(readFileSync(cfgPath, "utf8"));

const str = (key) => (typeof cfg[key] === "string" ? cfg[key] : "");
const pk = (k) => {
  const v = cfg.auditorPk?.[k];
  return typeof v === "string" ? v : "";
};

const assetCode = process.env.ASSET_CODE ?? cfg.assetCode ?? "CONF";
const assetIssuer =
  process.env.ASSET_ISSUER ?? cfg.assetIssuer ?? tryStellarKeyAddress("issuer");

const lines = [
  `# Auto-generated by packages/dapp/scripts/sync-env.mjs`,
  `# Source: ${cfgPath}`,
  `# Re-run: cd packages/dapp && npm run sync-env`,
  ``,
  `VITE_NETWORK=${network}`,
  `VITE_REGISTRAR_ID=${str("registrar")}`,
  `VITE_VERIFIER_REGISTRATION_ID=${str("verifierRegistration")}`,
  `VITE_VERIFIER_TRANSFER_ID=${str("verifierTransfer")}`,
  `VITE_VERIFIER_WITHDRAW_ID=${str("verifierWithdraw")}`,
  `VITE_CONFIDENTIAL_TOKEN_ID=${str("confidentialToken")}`,
  `VITE_SAC_ID=${str("sacToken")}`,
  `VITE_AUDITOR_ADDRESS=${str("auditorAddress")}`,
  `VITE_AUDITOR_PK_X=${pk("x")}`,
  `VITE_AUDITOR_PK_Y=${pk("y")}`,
  `VITE_ASSET_CODE=${assetCode}`,
  `VITE_ASSET_ISSUER=${assetIssuer}`,
  ``,
];

writeFileSync(envPath, lines.join("\n"));
console.log(`wrote ${envPath}`);

// Copy circuit artifacts into public/circuits/<name>/<name>.{wasm,zkey} so the
// browser can fetch them with predictable URLs that match config.ts.
//
// Upstream artifact naming is inconsistent — `transfer` uses transfer.zkey
// while registration and withdraw use circuit_final.zkey. We normalise.
const circuits = [
  { name: "registration", wasm: "registration.wasm", zkey: "circuit_final.zkey" },
  { name: "transfer", wasm: "transfer.wasm", zkey: "transfer.zkey" },
  { name: "withdraw", wasm: "withdraw.wasm", zkey: "circuit_final.zkey" },
];

for (const c of circuits) {
  const outDir = join(publicDir, "circuits", c.name);
  mkdirSync(outDir, { recursive: true });

  const wasmSrc = join(circomBuild, c.name, c.wasm);
  const zkeySrc = join(circomBuild, c.name, c.zkey);
  const wasmDest = join(outDir, `${c.name}.wasm`);
  const zkeyDest = join(outDir, `${c.name}.zkey`);

  for (const [src, dest] of [
    [wasmSrc, wasmDest],
    [zkeySrc, zkeyDest],
  ]) {
    if (!existsSync(src)) {
      console.error(`missing ${src} — run cargo build first and ensure submodule is initialised`);
      process.exit(1);
    }
    // Skip re-copy if file is already up to date (mtime + size match).
    const srcStat = statSync(src);
    if (existsSync(dest)) {
      const destStat = statSync(dest);
      if (destStat.size === srcStat.size && destStat.mtimeMs >= srcStat.mtimeMs) {
        continue;
      }
    }
    copyFileSync(src, dest);
    console.log(`copied ${dest.replace(publicDir, "public")}`);
  }
}
